# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2fa7ad588b9ec260dc6dd7cb27d5771c1dcb3cdffb7cce4a0204f76d96b879754fea093861f6a45a448c6c2e1593550b287e4d2a0feaa69b98d2f330b32da89

test:
  secret_key_base: bef46f8985acf7099994321c6dfb9da79050d27c7d303b4bd15a13d861873a28ba209a6eab6ca387913d3d1dd50716552516434bfa425157c3575845bee79f4d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
